[general]
live_config_reload = true

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.85
blur = true
startup_mode = "maximized"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[colors.primary]
background = "#0A0A0A"

[cursor]
style = { shape = "Beam", blinking = "On" }

[mouse]
hide_when_typing = true

