[general]
live_config_reload = true

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.85
blur = true
startup_mode = "maximized"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[colors.primary]
background = "#0A0A0A"

[cursor]
style = { shape = "Beam", blinking = "On" }

[mouse]
hide_when_typing = true

# Source - https://stackoverflow.com/a
# Posted by Acaibird
# Retrieved 2025-12-16, License - CC BY-SA 4.0

[keyboard]
bindings = [
  { key = "Left", mods = "Alt", chars = "\u001BB" },  # Alt + B (Move backward one word)
  { key = "Right", mods = "Alt", chars = "\u001BF" },  # Alt + F (Move forward one word)
  { key = "D", mods = "Alt", chars = "\u001BD" },  # Alt + D (Delete the word after the cursor)
  { key = "Backspace", mods = "Alt", chars = "\u001B\u007F" },  # Alt + Backspace (Delete word before cursor)
  { key = "U", mods = "Alt", chars = "\u001BU" },  # Alt + U (Uppercase from cursor to end of word)
  { key = "L", mods = "Alt", chars = "\u001BL" },  # Alt + L (Lowercase from cursor to end of word)
  { key = "C", mods = "Alt", chars = "\u001BC" },  # Alt + C (Capitalize the current word)
  { key = ".", mods = "Alt", chars = "\u001B." },  # Alt + . (Insert the last argument of previous command)
  { key = "Y", mods = "Alt", chars = "\u001BY" },  # Alt + Y (Yank the top of the kill-ring)
  { key = "/", mods = "Alt", chars = "\u001B/" },  # Alt + / (Attempt completion)
  { key = "T", mods = "Alt", chars = "\u001BT" },  # Alt + T (Transpose the words around cursor)
  { key = "R", mods = "Alt", chars = "\u001BR" },  # Alt + R (Recall the last command that matches input)
  { key = "N", mods = "Alt", chars = "\u001BN" },  # Alt + N (Search forward through history)
  { key = "P", mods = "Alt", chars = "\u001BP" },  # Alt + P (Search backward through history)
  { key = "Q", mods = "Alt", chars = "\u001BQ" }   # Alt + Q (Not a standard bash shortcut, customizable)
]

