add_newline = false

format = "$directory $character"

# ------------------------------------------------------------
# Directory
# ------------------------------------------------------------
[directory]
truncate_to_repo = true
truncation_length = 3
truncation_symbol = "…/"
style = "fg:245"
format = " [$path]($style)"
home_symbol = "~"

# ------------------------------------------------------------
# Git
# ------------------------------------------------------------

[git_status]
disabled = true

# ------------------------------------------------------------
# Exit status (only on error)
# ------------------------------------------------------------
[status]
disabled = true

# ------------------------------------------------------------
# Prompt character
# ------------------------------------------------------------
[character]
success_symbol = "[❯](fg:250)"
error_symbol = "[❯](fg:160)"
